### ISSUE TITLE
Link to reference

### ISSUE THREAD

**Issue by yanwu2014** [mulinlab/CAUSALdb-finemapping-pip#1]
Hi Jianhua,

Thanks for putting this database together! It's been really helpful. I wasn't able to figure out where the pre-build reference directory was though, is `115...212:/f/jianhua/jianhua_pipeline/Fine-mapping/ref` linking to something in this github repo or some external FTP server?

Thanks!

**Comment by Jianhua-Wang** [comment]
115...212 is a server for our lab members. This server is not open to others. But you can still make your reference by [ref/01_prepare_reference.py](https://github.com/mulinlab/CAUSALdb-finemapping-pip/blob/master/ref/01_prepare_reference.py). It won't take long.

**Comment by WAAkurugu** [comment]
Hi Jianhua,
ref/01_prepare_reference.py has been running for almost 3 days now and not getting completed. Is that normal?
I have sequenced variants for both binary/categorical and quantitaive data to fine map. Do I have to use the reference panel? Quite new to fine mapping
Hoping for a positive response
-Wisdom

**Comment by Jianhua-Wang** [comment]
The reference panel is mandatory. You can use 'htop' or 'top' command to check the process is running or dead. I applied a multiple processing operation so you might have some problems when you are running on a small PC.

**Comment by WAAkurugu** [comment]
I tried to run from our ubuntu server with python 2.7 but got an error:
File "01_prepare_reference.py", line 15
    call(f'wget -c ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr{chromosome}.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz -P ./ld/vcf',shell=True)
                                                                                                                                                                             ^
SyntaxError: invalid syntax

**Comment by Jianhua-Wang** [comment]
You should run with python 3.7+.

**Comment by WAAkurugu** [comment]
It run for a while and produced some errors:

Failed to open ./ld/vcf/AFR_1/AFR_22_49381314_49717821.vcf.gz: No such file or directory
Failed to open file ./ld/vcf/AFR_1/AFR_22_48647687_48971174.vcf.gz
Failed to open ./ld/vcf/AFR_1/AFR_22_47446472_48647687.vcf.gz: No such file or directory
Failed to open ./ld/vcf/AFR_1/AFR_22_48647687_48971174.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file ./ld/vcf/AFR_1/AFR_22_49717821_51243298.vcf.gz
Failed to open ./ld/vcf/AFR_1/AFR_22_49717821_51243298.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file ./ld/vcf/AFR_1/AFR_22_48971174_49381314.vcf.gz
Failed to open ./ld/vcf/AFR_1/AFR_22_48971174_49381314.vcf.gz: No such file or directory
/bin/sh: 1: tabix: not found
/bin/sh: 1: tabix: not found
/bin/sh: 1: tabix: not found

**Comment by Jianhua-Wang** [comment]
make sure you have downloaded the 1000G VCFs in ./ld/vcf

**Comment by WAAkurugu** [comment]
Do I require the password for 1000G VCFs? The script does not download them

**Comment by Jianhua-Wang** [comment]
they are publicly available. http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/

**Comment by WAAkurugu** [comment]
You need to update your 01_prepare_reference.py script to point to ".......integrated_v5b.20130502........." rather than "..........integrated_v5a.20130502..........". The FTP site has version b and not a

**Comment by Jianhua-Wang** [comment]
thank you for the message. I have updated the url.
