### ISSUE TITLE
Please provide a licence

### ISSUE THREAD

**Issue by kalylian** [mulinlab/CAUSALdb-finemapping-pip#2]
Hi,

I am an administrator and I was asked by a user to install PAINTOR. However, I was unable to find a licence, so I'm unsure whether I'm allowed to provide it.

Kind regards

**Comment by Jianhua-Wang** [comment]
This repository is a pipeline of fine-mapping. We are not authors of PAINTOR. I noticed you have opened an issue in PAINTOR's repository already. Please wait for their answer.

**Comment by kalylian** [comment]
oh. I'm sorry, I seem to have confused the names..

The scientist actually wants me to install this repo. CAUSALdb. I'm also checking with all dependencies because I need their permissions, too. 

Kind regards

**Comment by Jianhua-Wang** [comment]
CAUSALdb and this repo are both free to use. We'll consider declare an open-source license. For now, please cite the publication of CAUSALdb (doi:10.1093/nar/gkz1026) if you use it.

**Comment by kalylian** [comment]
Great, thanks :) I'll pass it on.
