### ISSUE TITLE
http adress for caviarbf download + conda environment 

### ISSUE THREAD

**Issue by marie-michel** [mulinlab/CAUSALdb-finemapping-pip#4]
Hi, 

I had some trouble running your scripts. 

First, I had to make the following changes in the yml file to create the conda environment : 
```
name: finemap
channels:
- defaults
- bioconda
- conda-forge
dependencies:
- bcftools
- tabix
- intel-openmp=2018.0.0
- mkl=2018.0.1
- mkl-service=1.1.2
- defaults::numpy==1.13.3
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - pandas==0.21.0
  - scipy==1.3.1
```
Before making these changes I had the following error : 

```
ResolvePackageNotFound: 
  - bcftools
  - openssl==1.0.2l=0
  - python==3.6.2=0
  - zlib==1.2.11=0
  - pip==9.0.1=py36_1
  - setuptools==36.4.0=py36_1
  - xz==5.2.3=0
  - tabix
  - tk==8.5.18=0
  - readline==6.2=2
  - certifi==2016.2.28=py36_0
  - wheel==0.29.0=py36_0
```

Second the link to download caviarbf changed it is now : ``` wget -c https://bitbucket.org/Wenan/caviarbf/get/25bac331a203.zip ```, previously i had "404 error not found". 

Besides that, thank you very much for creating this tool and this database. 

Kind regards,
Marie

**Comment by Jianhua-Wang** [comment]
Hi Marie, thank you for the feedback.
I updated the yml file and the setup script. You can clone the current version and try.

**Comment by marie-michel** [comment]
In fact I didn't have the latest version. I used the command line ``` git clone https://github.com/Jianhua-Wang/Fine-mapping.git ``` that you provide in the "Get started" section in the README.md file. Instead, the following command line ```https://github.com/mulinlab/CAUSALdb-finemapping-pip.git``` works well. 
That is why I had trouble downloading caviarbf as well. 

For the conda environment it's not working for the following packages : 
```
ResolvePackageNotFound: 
  - setuptools==36.4.0=py36_1
  - certifi==2016.2.28=py36_0
  - readline==6.2=2
  - tk==8.5.18=0
``` 
When I remove them from the yml file, it's working fine. The version for each packages are then : 
```
setuptools : 50.3.1
certifi : 2020.6.20
readline : 8.0
tk :  8.6.10 
```

**Comment by Jianhua-Wang** [comment]
Sorry, I forgot to correct the url. The yml works well on my machine and it's normal if you have compatibility issues.

**Comment by marie-michel** [comment]
It is working well on my computer now.  Thank you for your replies !!
Marie
