### ISSUE TITLE
Block variable never used

### ISSUE THREAD

**Issue by reemagit** [mulinlab/CAUSALdb-finemapping-pip#6]
https://github.com/mulinlab/CAUSALdb-finemapping-pip/blob/c817b2671e97a1dce7e0c580c1bb736e723152a6/ref/01_prepare_reference.py#L44

The variable "block" doesn't seem to be used, but I am not sure if I got the code right, shouldn't line 44 be like below?

`chr_id, start, stop = block.loc[i].values[:-1]`

Notice that I replaced "blocks" with "block".

Same for line 83 (https://github.com/mulinlab/CAUSALdb-finemapping-pip/blob/c817b2671e97a1dce7e0c580c1bb736e723152a6/ref/01_prepare_reference.py#L83)

**Comment by Jianhua-Wang** [comment]
Thank you for pointing this out! I guess that I pasted the wrong code when converting jupyter notebook to py script. I've updated the code and now it should work correctly.

**Comment by reemagit** [comment]
Not at all! And thanks for updating the code.
